### PR TITLE
LSP integration

### PR DESCRIPTION
**Pull request by aabounegm**
Along with https://github.com/rzk-lang/vscode-rzk/pull/36.
Adds a simple implementation of a language server using LSP, currently with semantic tokens and error reporting (for parsing and type errors).

### CODE REVIEW

**Comment by aabounegm** [comment]
And as always whenever I add a new dependency, seems like I need help with the Nix configuration :D

**Comment by fizruk** [comment]
@deemp do you know why https://github.com/rzk-lang/rzk/pull/95/commits/14b45ea59049be20c0dfcd77071157bbbabc1051 did not work? can you help fix this?

**Comment by deemp** [comment]
https://github.com/rzk-lang/rzk/pull/82#issuecomment-1724524807

> It doesn't use rzk.nix

Sorry, it was false. You can write `hpack --force` in `rzk.nix`. At least this is how I fixed a build error in https://github.com/rzk-lang/rzk/pull/84

**Review by fizruk — APPROVED** [review]
Works marvellously on my machine!

**Pull request merged**
